// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutohideController from "./autohide_controller"
application.register("autohide", AutohideController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import NewExpensesTrackerController from "./new_expenses_tracker_controller"
application.register("new-expenses-tracker", NewExpensesTrackerController)
